### ISSUE TITLE
Maintenance and Future Development of the Baseline Protocol Website

### ISSUE THREAD

**Issue by markymark-26** [eea-oasis/baseline-outreach#19]
# Item
Baseline Protocol Website Maintenance and Future Development

# Description 
Future updates (content as well as code) to the website and support during possible migration to Wordpress or the integration of a headless CMS.

# Definition of 'Done'

- [ ] Four hours per week will be reserved to implement future updates & maintenance for whole year (2022)

# Steps

- [ ] Maintenance of website is attended to for whole year (2022)
- [ ] Migrate to WordPress (if deemed necessary by admin)
- [ ] Integrate headless CMS

# Updates 
Issue comments will be used for logging updates and labels will be used for current status and work group responsible for current stage.

# Grants
Outreach work items that are related to an [approved grant project](https://github.com/eea-oasis/baseline-grants) require updates by the 1st of each month by adding a comment on this issue with a detailed update on progress, roadblocks, and any comments.

**Comment by boye** [comment]
Changes that I have landed in March are:

- Added sponsor blocks on Get Baselined page
- Prepped logic for blog categories
- Minor UI improvements (also for dark mode)
- Added Google Analytics
- Added social share buttons
- Several content changes (related to BLIPs and grant fund) as per request

**Comment by GoldenBit0** [comment]
@boye please complete the May update.

**Comment by fosgate29** [comment]
@boye Hi. Could you complete the May update?

**Comment by boye** [comment]
Hi guys, sorry for the delay. I am away with my family and I don't have my Macbook with me. I can do the May update coming Monday at the earliest.

Cheers,
Boye

**Comment by boye** [comment]
Change that I have landed in May are:

- the implementation of the blog filter based on categories (including some research on how to get this done properly within Hugo)

**Comment by boye** [comment]
June update:

The Outreach team is working with me to propose some changes for a next iteration of the site. Sonal told me other teammates are testing out the site, creating new graphics, viewing the UI/UX, etc. I am excited to implement these new improvements.

**Comment by GoldenBit0** [comment]
7/18/22:

- Sonal working with group and bringing in outreach team to draft updates for site

**Comment by GoldenBit0** [comment]
9/12/22:

- Instead of having signupgenius will code process for joining baseline team s
- Team to continue connecting on redoing ui/ux to website

**Comment by GoldenBit0** [comment]
9/26/22:

- Web dev is adding sign up onto site

**Comment by samratkishor** [comment]
@boye can we explore embedding the Google calendar invites for all working group meetings and Baseline shows onto the website? This will enable people to add the events to their calendar in a self-service manner.
Ref: https://support.google.com/calendar/answer/41207?hl=en

**Comment by boye** [comment]
@samratkishor sure, I can look into that. Do you have a preference where to add it within the UI? Perhaps on the homepage under the "The Baseline Show" heading?

@GoldenBit0 is it correct that you are the owner of the calendar? if so, can you perhaps share that embed code (which is mentioned in the URL that Samrat provided)

**Comment by boye** [comment]
10/28/22:

- Several textual changes as per Sonal's request
- Added link to Google Forms on "Get Involved" page

**Comment by boye** [comment]
Nov 22:

- [Updated dependencies (including Hugo binary)](https://github.com/eea-oasis/baseline-website-v2/commit/fe58d64de8d8663da4b3ff41374b2661470f80af)
- Assisted Claudia with a Netlify deployment issue

**Comment by GoldenBit0** [comment]
12/5/22:

- Sonal and Boye working together on final updates for the website, will wrap up within the next 2 weeks (design changes, formatting changes, updating information, adding filters to blogs)
