### ISSUE TITLE
Lendit FinTech May 25th, 2022

### ISSUE THREAD

**Issue by markymark-26** [eea-oasis/baseline-outreach#22]
# Item
Lendit FinTech May 25th, 2022
---

# Description 
The Outreach Team is responsible for evangelizing and enabling the adoption of the Baseline Protocol. Attending technical conferences in key industries are crucial to spread the message of baseline, identify key opportunities for the protocol, and gauge interest in the merit of the protocol. This item will be used to track the objectives and outcomes of attendance at Lendit Fintech - The USA’s Leading Event for Innovation in Financial Services. May 25-26. 

Boris Breslav is attending Lendit Fintech to represent the Baseline Protocol and will complete a handful of activities outlined below.  

---

# Definition of 'Done'
Criteria for completing item
- [ ] Attend Keynotes
- [ ] Approach presenters/attendees to inform and discuss potential Baseline participation/engagements
- [ ] Share all contact information with the Baseline Team
- [ ] Summarize Keynotes and conference takeaways
- [ ] Present summary information at The Baseline Show

---

# Steps
Describe steps for competing this item
- [ ] Attend Lendit Fintech
- [ ] Attend Keynotes
- [ ] Approach presenters/attendees to inform and discuss potential Baseline participation/engagements
- [ ] Share contact information with the Baseline Team
- [ ] Summarize keynotes, thoughts, and opportunities for baseline from conference
- [ ] Share summary on the Baseline Show

---

# Updates 
Issue comments will be used for logging updates and labels will be used for current status and work group responsible for current stage.

---

# Grants
Outreach work items that are related to an [approved grant project](https://github.com/eea-oasis/baseline-grants) require updates by the 1st of each month by adding a comment on this issue with a detailed update on progress, roadblocks, and any comments.

**Comment by BresGit** [comment]
**Attend the following sessions on 5/25** 

Fireside Chat
**Achieving Scale Through Customer Alignment**
TIME:
9:00 AM - 9:30 AM
30min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Day 1 - Keynotes
Speakers:
Moderator
Paul StamasManaging Director @ General Atlantic
Keynote speaker
Chris BrittCEO @ Chime
On the LendIt Fintech USA keynote stage for the first time you will meet the CEO and Co-Founder of Chime, Chris Britt. Chime has become one of the biggest success stories in all of fintech. In this session, you will learn more about what makes Chime unique and how their member-aligned business model has made Chime the most loved and downloaded banking app in the US. Chris will discuss Chime's founding story, what opportunity Chris and his co-founder Ryan King saw back in 2012 when the company was founded, and how Chime is driving positive change in the industry and improving the financial lives of millions of people with products like SpotMe, Chime's fee-free overdraft. You’ll also hear more about Chime’s community of members, who are at the heart of Chime’s success


Fireside Chat
**The Future of Consumer Finance is Digital—Why Your Checking Account May Be the Key**
TIME:
9:30 AM - 9:50 AM
20min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Day 1 - Keynotes
Speakers:
Moderator
Todd AndersonChief Content Officer @ Fintech Nexus
Keynote speaker
Swati BhatiaPartner, Head of Consumer Proprietary Business (Marcus) @ Marcus by Goldman Sachs
Swati Bhatia, Head of Consumer Proprietary Business at Marcus by Goldman Sachs, joins LendIt’s Todd Anderson for a discussion about the continued disruption of consumer financial services, Goldman Sachs’ approach to meeting the needs of customers by meeting them where they are and how Marcus’ forthcoming checking product will play a pivotal role in the next phase of consumer growth for the storied financial institution.


Fireside Chat
**Can Financial Services Replicate the Amazon Experience?**
TIME:
9:50 AM - 10:20 AM
30min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Day 1 - Keynotes
Speakers:
Keynote speaker
Sarah ClarkSVP Digital Identity @ Mastercard
Keynote speaker
Ahron GeminderGlobal Digital Head of Product for Third Party Services @ HSBC
Keynote speaker
Mike TuchenCEO @ Onfido
Moderator
Bo BrustkernCo-Founder & CEO @ Fintech Nexus
In a digital-first world how can financial institutions provide more Amazon-like services? How can we onboard customers faster, anticipate customer needs, build trust and suggest more personalized value-added experiences?

Digital identity could hold the key to unlocking all these things and creating a more loyal customer base. But what’s the best way to implement it? How do biometrics, AI and the concept of portable identity play a part? Banks and fintechs cannot provide seamless account creation and loan decisions within seconds without a sophisticated digital identity program.

In this session hear from experts at Mastercard, HSBC and Onfido as they share examples of how this is being done today and what more is needed to bring the Amazon experience to banking.


Fireside Chat
**The Identity “Hot” Seat: A "Fire"-Side Chat**
TIME:
10:50 AM - 11:10 AM
20min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 6 (1E12) - Data, Fraud and the Future of Identity - Sponsored by Prove
Speakers:
Speaker
Rodger DesaiCo-Founder & CEO @ Prove
Speaker
Travis JaraeCEO @ Liminal
Speaker
Sarah ClarkSVP Digital Identity @ Mastercard
Watch things heat up as three of digital identity’s most influential voices discuss the space’s hottest topics while sampling a trio of scorching hot sauces. Join Prove CEO Rodger Desai; Mastercard SVP, Digital Identity Sarah Clark; and Liminal CEO Travis Jarae for this fast-paced talk that gives a new meaning to “fire”side chat.


Fireside Chat
**How can Fintech companies use Digital-Assets-as-a-Service?**
TIME:
11:15 AM - 11:35 AM
20min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 2 (1E07) - Web3 & CBDCs: The Future of Money is Here - Sponsored by NYDIG
Speakers:
Moderator
Simon TaylorCo-Founder & Chief Product Officer @ 11:FS
Panelist
Kirupa PushparajGeneral Counsel & Corporate Secretary @ Step
Panelist
Mark DalyVP of Growth @ Zero Hash


**SMB Lending Reimagined - A Futuristic View of How Open Finance Will Change Access and Distribution of Capital**
TIME:
11:35 AM - 11:55 AM
20min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 5 (1E13) - Fintech in 2027 - Sponsored by Mastercard
Speakers:
Speaker
Brock BlakeCEO & CoFounder @ Lendio


Panel
**Securitizing Real World Assets with DeFi**
TIME:
12:00 PM - 12:40 PM
40min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 2 (1E07) - Web3 & CBDCs: The Future of Money is Here - Sponsored by NYDIG
Speakers:
Moderator
Jason JonesEND-Labs @ CEO
Panelist
monetsupply _Risk Analyst @ MakerDAO
Panelist
Jeannice TsePartner & Portfolio Lead @ Centrifuge
Panelist
Kirill BensonoffCo-Founder & CEO @ New Silver
We will talk about how 2021 was the pivot year for traditional finance and decentralized finance coming together, and how real world assets can be financed using capital from protocols. We will discuss how this year and in the near future, real world capital markets will be able to benefit from the billions of dollars of value currently available in DeFi protocols, and how blockchain can speed up and lower costs of issuing fixed income securities



Fireside Chat
**Building a Digital Marketplace Bank: The Agility of a Fintech, the Resilience of a Bank**
TIME:
1:30 PM - 2:00 PM
30min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Day 1 - Keynotes
Speakers:
Keynote speaker
Karen WebsterCEO @ PYMNTS.com
Keynote speaker
Scott SanbornCEO @ LendingClub
Retail banking is one of the last industries that hasn’t been fundamentally changed by the internet. Traditional banks try to keep pace with evolving consumer needs but are essentially still selling the same products and services on a legacy infrastructure that they have had for decades. On the other hand, fintechs mainly operate as flashy front ends to the traditional banking architecture without capturing real wallet share or driving true revolutionary change. Now, there’s a small group of fintechs that have become banks that are powered by innovative technology infrastructures and have the power to usher in the real change that others have talked about for over a decade. Join a discussion with LendingClub’s CEO Scott Sanborn to hear more about LendingClub’s customer-centric marketplace bank, the technology that powers it, and his ambition to create intelligent finance that brings to the masses the seamless personalized money management that the ultra-wealthy have but is often out of reach for everyday Americans.



**Bridging Traditional and Decentralized Finance to Unlock the Most Value for Consumers**
TIME:
2:50 PM - 3:10 PM
20min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 2 (1E07) - Web3 & CBDCs: The Future of Money is Here - Sponsored by NYDIG
Speakers:
Moderator
Todd AndersonChief Content Officer @ Fintech Nexus
Panelist
Dan ReecerChief Growth Officer @ Acala
Panelist
Trevor MarshallChief Technology Officer @ Current


**Transitioning to a digital-first world in banking and lending**
TIME:
2:50 PM - 3:10 PM
20min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 1 (1E08) - Banking Crosses into its Digital Future: Sponsored by Galileo Financial Technologies
Speakers:
Moderator
Ron ShevlinManaging Director, Fintech Research @ Cornerstone Advisors
Panelist
Tim WelshVice Chair, Consumer & Business Banking @ U.S. Bank
In this talk, Tim Welsh, head of Consumer and Business Banking at U.S. Bank, will address the integration of digital and personalized lending innovation in key consumer and small business experiences such as “instant decision” mortgage, “Fund My Business” Simple Loan, personal loans and lines, in addition to other tools.


**How to Build a Risk Department for the Future**
TIME:
3:15 PM - 3:55 PM
40min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 6 (1E12) - Data, Fraud and the Future of Identity - Sponsored by Prove
Speakers:
Panelist
Ashish GuptaChief Risk Officer @ LendingPoint
Moderator
Conor BurkeCo-Founder & CTO @ Inscribe
Panelist
Ido LustigFounder & CEO @ Bizi
Panelist
Srinath SrinivasanHead of Risk @ Ramp
Panelist
Lei ChenHead of Fraud Risk @ Marcus by Goldman Sachs


**The Digital Transformation of Customer Experience**
TIME:
4:45 PM - 5:25 PM
40min
DATE:
Wednesday 25th of May
LOCATION:
5-25: Room 6 (1E12) - Data, Fraud and the Future of Identity - Sponsored by Prove
Speakers:
Moderator
Brenda ShartonPartner @ Dechert LLP
Panelist
Rick DeLisiLead Research Analyst @ Glia
Panelist
Yogesh MulwaniRegional Vice President, Technology @ Backbase

**5/26**

**Comment by BresGit** [comment]
**Attend the following sessions on 5/26** 


**Breakfast Roundtable: Delivering a modern banking experience - do you have the right foundation?**
TIME:
7:45 AM - 9:00 AM
1h 15min
DATE:



**Opening Remarks**
TIME:
8:45 AM - 8:50 AM
5min
DATE:
Thursday 26th of May
LOCATION:
5-26: Day 2 - Keynotes


**Fireside Chat
Why the Future of Payments Will be Blockchain-Based**
TIME:
9:00 AM - 9:30 AM
30min
DATE:
Thursday 26th of May
LOCATION:
5-26: Day 2 - Keynotes
Speakers:
Moderator
Gregg SchoenbergManaging Partner @ Westcott Inc.
Keynote speaker
Wade PeeryChief Administrative Officer @ FirstBank
Keynote speaker
Matthew MaxeyHead of Innovation @ Synovus Bank
Keynote speaker
Mike CagneyCo-Founder & CEO @ Figure
Payments have come a long way in the past decade. We have moved from a cash and card-centric payments system to one that is becoming digitally native and mobile-centric. But payments are about to go through a new transformation that will completely reshape the industry.

Join fintech industry pioneer Mike Cagney, CEO and co-founder of Figure, as well as Matthew Maxey of Synovus and Wade Peery of FirstBank as they discuss the future of payments and why banks are jumping on board the blockchain bandwagon. They will cut through

Payment rails should be low cost, real-time and available 24/7/365. Learn why we are closer to this reality than you might think.


**Fireside Chat
Why Every Bank Needs a Crypto Strategy**
TIME:
9:30 AM - 9:50 AM
20min
DATE:
Thursday 26th of May
LOCATION:
5-26: Day 2 - Keynotes
Speakers:
Keynote speaker
Terry AngelosCEO @ DriveWealth
Keynote speaker
Alan LaneCEO @ Silvergate Bank
With an increasing number of crypto owners looking to their banks for crypto support, how can financial institutions continue to meet the needs of their clients, while also managing the risks associated with digital currencies? Today, the crypto world parallels that of the mid-90s internet. We are seeing rapid adoption rates, but the industry is still met with skeptics and critics about how crypto will fit into our financial system. While we can't say for sure that crypto will have the same trajectory as the internet we all rely on today, financial institutions need to be actively thinking about crypto.

In a fireside chat, Visa alongside Silvergate Bank, will discuss the current state of the crypto industry, and the key reasons now is the time to build out your crypto strategy, from rising consumer interest to the reality of CBDCs, or simply ensuring you and your customers are educated on crypto opportunities.


**Will DeFi Eat the World?**
TIME:
9:50 AM - 10:10 AM
20min
DATE:
Thursday 26th of May
LOCATION:
5-26: Day 2 - Keynotes
Speakers:
Moderator
Bo BrustkernCo-Founder & CEO @ Fintech Nexus
Keynote speaker
Liz MathewBD & Partnerships, Metamask Institutional @ ConsenSys

**Fireside Chat
How the World's Largest Digital Bank Brought Millions of People into the Financial System**
TIME:
10:10 AM - 10:30 AM
20min
DATE:
Thursday 26th of May
LOCATION:
5-26: Day 2 - Keynotes
Speakers:
Keynote speaker
David VelezCEO & Co-Founder @ Nubank
Keynote speaker
Nigel MorrisManaging Partner & Co-Founder @ QED Investors
Nubank is a technology success story as well as a financial inclusion success story. The Brazilian-based digital bank bank has grown from 4 million customers to 50 million in just the last four years. How have they done this?

On the LendIt Fintech USA keynote stage for the first time you will meet the CEO and Co-Founder of Nubank, David Vélez, in a conversation with the fintech investing legend, Nigel Morris, managing partner of QED Investors and co-founder of Capital One.
Some of the topics they will be discussing:
•	The core ingredients in Nubank's rapid scaling.
•	What Nigel saw in Nubank back in 2015.
•	How Nubank is able to convince millions of people to enter the financial system.
•	Secrets to their insanely low customer acquisition cost.
•	Nigel's perspective on comparisons to the early days of Capital One.
•	Advice for US digital banks looking to grow fast.
•	What more is needed for fintech to make a bigger impact.



**Panel
BNPL for Business: A Massive and Complex Opportunity**
TIME:
10:50 AM - 11:30 AM
40min
DATE:
Thursday 26th of May
LOCATION:
5-26: Room 4 (1E15) - SMB Fintech: New Solutions for Lending & Banking - Sponsored by Fundbox
Speakers:
Moderator
Peter RentonChairman & Co-Founder @ Fintech Nexus
Panelist
Vanessa ColellaSVP, Head of Innovation & Global Digital Partnerships @ Visa Inc.
Panelist
Jason LakyEVP of Financial Services @ TransUnion
Panelist
Jann ParishFounder & CEO @ GLU Girls Like You
Panelist
Prashant FuloriaCEO @ Fundbox
BNPL has made a significant impact in the consumer world, totaling an estimated $226B in transactions in 2021 from markets like electronics and fashion to furniture and travel. But the B2B market for BNPL remains a massive untapped opportunity in the payments space, especially for SMB buyers, where unpredictable cash flow and working capital challenges make necessary purchases difficult to obtain. This session will explore what you need to know about BNPL for Business: what it is, how it might work, and why it will look different from consumer offerings.



**The Future of Open Banking: Usability‚ not Connectivity**
TIME:
11:15 AM - 11:55 AM
40min
DATE:
Thursday 26th of May
LOCATION:
5-26: Room 3 (1E16) - Embedded Finance: Every Company Can Become a Fintech - Sponsored by Fiserv
Speakers:
Moderator
Paul DiegelmanVP Data Aggregation & Digital Payments @ Fiserv
Panelist
Andy SheehanEVP, U.S. Open Banking @ Mastercard
Panelist
Adam GibsonHead of Product @ Flinks Technology Inc.
Panelist
Wendy Cai-LeeFounder & CEO @ Piermont Bank
Panelist
Shmulik FishmanCEO & Founder @ Argyle



**Panel
Reconciling Responsible BNPL With the Need for Access**
TIME:
12:00 PM - 12:40 PM
40min
DATE:
Thursday 26th of May
LOCATION:
5-26: Room 1 (1E08) - Consumer Lending: BNPL, Cards and Personal Loans - Sponsored by FICO
Speakers:
Moderator
Kim GerhardtOwner & Principal Advisor @ The Fintech Interactive
Panelist
Yaacov MartinCEO @ Jifiti
Panelist
Arad LevertovCEO & Co-Founder @ Sunbit
Panelist
Greg WrightExecutive Vice President & Chief Product Officer @ Experian
Panelist
Zahir KhojaGM of Global Platforms & Partnerships @ Afterpay
With accessibility and affordability being key advantages of Buy Now Pay Later, how can lenders provide this while still lending responsibly? Typical lending risk models limit the accessibility of financing, but the nature of BNPL dictates that merchants and consumers need instant decision-making with high approval rates for both big-ticket and small-ticket items - within the framework of fair and responsible lending. How do we achieve this?


**Fireside Chat
Stumbling Blocks to Stepping Stones: Building the Future of Finance From Vision to Reality**
TIME:
2:10 PM - 2:30 PM
20min
DATE:
Thursday 26th of May
LOCATION:
5-26: Day 2 - Keynotes
Speakers:
Gilles GadeFounder & CEO @ Cross River Bank
Caitlin LongFounder & CEO @ Custodia Bank

The Next Wave of Mainstream Adoption: Bridging Crypto and Cash
TIME:
2:50 PM - 3:10 PM
20min
DATE:
Thursday 26th of May
LOCATION:
5-26: Room 6 (1E12) - Real Time Payments: How Fintech is Not Waiting for the Fed - Sponsored by Visa
Speakers:
Moderator
Robin NunnPartner @ Morgan, Lewis & Bockius LLP
Panelist
Larry AngelilliExecutive Vice President, Chief Financial Officer @ MoneyGram
Panelist
Justin RiceVP of Ecosystem @ Stellar Development Foundation

**Panel
Beyond Transactions to Relationships: Where do Consumer Lenders Go Next?**
TIME:
4:00 PM - 4:40 PM
40min
DATE:
Thursday 26th of May
LOCATION:
5-26: Room 1 (1E08) - Consumer Lending: BNPL, Cards and Personal Loans - Sponsored by FICO
Speakers:
Moderator
Larry ChiavaroCEO & Founder @ LPC Associates
Panelist
Jeffrey MeilerCEO & Founder @ Best Egg, a Marlette Holdings Company
Panelist
Matthew BochenekCEO @ Avant
Panelist
David KimballCEO @ Prosper
Panelist
Tom BurnsideCEO @ LendingPoint

**Comment by BresGit** [comment]
**Attend Lendit Fintech**

-  Attend Keynotes
-  Approach presenters/attendees to inform and discuss potential Baseline participation/engagements
-  Share contact information with the Baseline Team
-  Summarize keynotes, thoughts, and opportunities for baseline from conference
-  Share summary on the Baseline Show


**LendIt Fintech/Fintech Nexus – NYC’s Largest Fintech Events**
4,000 + Attendees
350 Speakers 
225 Sponsors

**Key Topics** 
Digital Identity 
Customer onboarding
Customer Experience 
Small Business Lending 
BNPL – Buy Now Pay Latter 


**Key Note -  Achieving Scale Through Customer Alignment**
Chime – Chris Britt  CEO.
Chime Financial, Inc. is an American financial technology company which provides fee-free mobile banking services that are provided by The Bancorp Bank or Stride Bank, N.A
**Key Topics Discussed** 
•	Most downloaded banking app in the USA 
•	Monetizing thru transaction activity
•	Helping smaller banks by partnering – **Potential opportunity for Baseline Protocol, synchronize privately with security** 
•	Social community focused company

**Key Note - Marcus by Goldman Sacs**
Swati Bhatia – Head of Consumer Proprietary Business

**Key Topics Discussed** 
•	Expanding Checking account business helps to connect to customers/clients/small business
•	Partnering with GM/Apple.
Note: Investment Banking expanding to individual clients and small business.



**Key Note - Can the Financial Services Replicate the Amazon Experience?**
Mastercard - Sarah Clark – SVP Digital Identity Mastercard **(discussed Baseline Protocol with Sarah and agreed to connect after the conference to potentially have MasterCard contribute/involved in Baseline)**
HSBC - Ahron Geminder – Global Digital Head of Product for Third Party Services @ HSBC
Onfido 0 Mike Tuchen - CEO Onfido

**Key Topics Discussed** 
•	Client Identity – need to improve user experience Digital Id challenges must be resolved 
•	How to engage customers 
•	Some online applications require  120 clicks to onboard a client, it should be 24 or less
•	Need for different persona like Payment, Investor, Credit Card etc 
•	Government IDs critical but other type of Id’s must be also considered University Id/Office ID/ Other Id’s
•	Key Theme Improvement for Customer Experience need to happen soon as more clients/people started using online/web during pandemic 
•	Decentralized Identity has been recognized as a requirement in the future. 

**Fireside Chat – The Identity “Hot” Seat:**
Mastercard - Sarah Clark – SVP Digital Identity Mastercard
Prove - Rodger Desai  CEO – Prove 
Lominal - Travis Jarae CEO – Liminal 

**Key Topics Discussed** 
•	Mobile Phones used for identity, (sim card identification) 
•	84% of population have phones, I the customer hold my own identity 
•	Reusable identity, advantages discussed,  presently a user creates a unique personal profile every time for each online application. 


**Fireside Chat – SMB (small to medium-sized business) Lending Reimagined – A Futuristic View of How Open Finance Will Change Access and Distribution of Capital**
Lendio – small business lending. 12+ billion funded so far, 75+ lenders in our network, 300,000+ loans funded 
Lendio - Brock Blake – CEO Lendio – Connected with 
Lendio - Denada Ramnishta – Strategy at Lendio   

**Key Topics Discussed** 
•	Lendio - largest small business lender
•	Connect to many major banks, and small lenders via API.  **(Discussed with Brock advantage of Baseline Protocol agreed to connect after the conference)** 
•	Going from stale to dynamic lending offer a loan before the client needs it
•	Three C’s
o	Connection to data
o	Categorization of data 
o	Correlation of data points


**Fire Side Chat – Bridging Traditional and Decentralized Finance to Unlock the Most Value for Consumers**
Acala - Dan Reecer - Chief Growth Officer @Acala
Current - Trevor Marshall - CTO Current  

**Key Topics Discussed** 

•	Banking should be accessible and affordable for everyone. We are bringing premium financial services to everyone with a variety of modern lifestyles to help improve their financial outcomes.
•	Bridging Web2 and Web3 
o	Polkadot XSM/Open API Traditional 
•	3 types of Stable Coins 
1.	Fiat backed Collateralized Stablecoins 
2.	Crypto Backed Stablecoins 
3.	Algorithmic Stablecoins 
•	Regulation of Fiat backed Collateralized Stablecoins.  


**Fire Side Chat – How to Build a Risk Department for the Future**

Lending Point - Ashish Gupta  - Chief Risk Officer Lending Point 
Inscribe - Conor Burke CTO – Inscribe 
Bizi - Ido Lustig – CEO Bizi
Risk Ramp - Srinash Srinivasan Head of Risk Ramp 


**Key Topics Discussed**
•	Challenges especially from identity perspective 
•	How to connect join information from identity perspective
•	Customer expectation have changed, expectation is less friction.
•	You are as good as your data
•	How to Equip Teams/Employees
o	Detection 
o	Data/Information 
o	Linkage of Data
o	Realtime 
o	Digital Verification 
o	Manual/Human Verification 
•	AI/Machine Learning 
•	You don’t what you don’t know reach out to people/organization that know
•	Risk needs to promote growth
•	Support product growth responsible.


**Fire Side Chat – The Digital Transformation of Customer Experience**

Dechert LLP Brenda Sharton - Partner Dechert LLP
Gila - Rick DeLisi - Lead Research Analyst @ Gila
BAckbase - Yogesh Mulwani – Regional VP Technology @Backbase


**Key Topics Discussed**
•	Customer behavior evolved faster that we responded – during pandemic
•	What is digital customer services – communication collaboration 
•	Personalization – user data to match the specific issue/need/process
•	DON’T CREATE A COKIE CUTTER EXPERIENCE


**Fireside Chat - Why The Future of Payments Will be Blockchain-Based**

Westcott Inc - Gregg Schoenberg  - Managing Partner Westcott Inc
FirstBank - Wade Peery -  Chief Admin Officer FirstBank
Synovus Bank Matthew Maxey – Head of Innovation Synovus Bank 
Figure Mike Cagney – CEO Figure


**Key Topics Discussed**

•	Why Payments on blockchain? 
o	Marketplace agnostic to customer
o	Stable coins 
•	Blockchain will be as disruptive to internet was 
•	Banks are joining consortiums to make joined decisions
•	Blockchain is as a new payment rail
•	Expected cost per transaction 1%  on blockchain compared to 3% Visa/Master Card – merchant will drive for cost reduction 


**Fireside Chat – Why Every Bank Needs a Crypto Strategy**

DriveWealth  - Terry Angelos  - CEO @DriveWealth
Silvergate Bank  - Alan Lane – CEO Silvergate Bank 


**Key Topics Discussed**
•	The Silvergate Exchange Network (SEN) enables our digital currency and institutional investor clients to send U.S. dollars and euros 24 hours a day, 7 days a week, 365 days a year between their Silvergate accounts and the accounts of other Silvergate clients.
•	How likely to switch to crypto ? 
o	Alan responded not sure when that will happen for community bank


**Fireside Chat - How the World’s Largest Digital Bank Brought Millions of People into the Financial System** 

Nubank - David Velez – CEO Nubank

**Key Topics Discussed**
•	Brazilian digital bank had growth from 4 million to 50 million in less than 4 years.
•	Great customer experience 0 fees, no rewards
•	Started with lending, then deposits, then credit. 


**Fireside Chat – BNPL for Business: A Massive and complex opportunity**

Visa - Vannessa - Colella SVP Head of Innovation & Global Digital Partnership Visa Inc
Transunion - Jason Laky – EVP of Financial Services @ Transunion 
Fundbox - Prashant Fuloria – CEO Fundbox 

Discussed with Prashanth Baseline Protocol. 

**Key Topics Discussed**
•	Fundbox is an embedded working capital platform for small businesses. As a leading provider of working capital, we use technology to help small businesses optimize cash flow. Since 2013, we have unlocked over $3 Billion in capital and connected to over 500,000 businesses.
•	Fundbox Announced partnership with Visa 
•	Delve into details of each small business, weekly, workflows
•	Help small business manage cash flows.

**Discussed with Prashanth Baseline Protocol.**


**Fireside Chat – Reconciling Responsible BNPL With Need for Access** 

Jifiti - Yaacov Martin – CEO Jifiti 
Sunbit - Arad Levertov – CEO Sunbit
Experian  - Greg Wright - VP Experian 

**Key Topics Discussed**
•	Jifiti is a technology company that powers point-of-sale financing for banks, lenders and merchants with our white-labeled BNPL platform and end-to-end solution. 
•	BNPL (buy now pay latter) global phenomenal 
•	Shift in credit client don’t want to perpetuate debt (take small loans and pay off) 
•	Accurate reporting is important to regulators
•	Fair and responsible lending
•	Budgeting tool

Discussed Baseline Protocol with Jifiti CEO and the Product Manager Hanan Eshwege  and agreed to connect after the conference to potentially have Jifiti  contribute/involved in Baseline.
